### ISSUE TITLE
Figure out a calendar utility

### ISSUE THREAD

**Issue by vloebel** [vloebel/back2work#4]
Choose a calendar utility and coordinate with Vicky for front end

**Comment by klynn726** [comment]
researched calendars and schedulers, met with group members multiple times to discuss possible integration, decided to put this on hold as a possible enhancement and use a date picker for now.

**Comment by klynn726** [comment]
Re-visited the idea, was asked to put together a test site for a date and time picker. did this in the testpages branch using https://help.syncfusion.com/js/datetimepicker/display-format. fully functional with date picker, time picker to the half hour, and a button with an event listener that console logs the data. Stopped at this point as it was unclear if this was going to be further used or integrated with the backend.
